package com.mobdeve.s13.group03.goalkeep

enum class IntentKeys {
    // Goals
    GOAL_ID_KEY,
    GOAL_TITLE_KEY,
    GOAL_TIME_CREATED_KEY,
    GOAL_TIME_EXPECTED_KEY,
    GOAL_TIME_COMPLETED_KEY,
    GOAL_DESCRIPTION_KEY,
    GOAL_PRIORITY_KEY,
    GOAL_STATE_KEY,
    GOAL_TAG_KEY,
    GOAL_PROGRESS_KEY,
    GOAL_OBJECT_KEY,

    // Tasks
    TASK_ID_KEY,
    TASK_TITLE_KEY,
    TASK_TIME_CREATED_KEY,
    TASK_TIME_EXPECTED_KEY,
    TASK_TIME_COMPLETED_KEY,
    TASK_DESCRIPTION_KEY,
    TASK_PRIORITY_KEY,
    TASK_STATE_KEY,
    TASK_GOAL_ID_KEY,
    TASK_OBJECT_KEY
}